

service: inmet-proj4


frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - kinesis:PutRecord
        - kinesis:PutRecords
      Resource:
        - Fn::GetAtt: [ kinesisStream, Arn ]



functions:
  callExternalAPI:
    handler: callExternalAPI.handler
    events:
      - http:
          path: /external
          method: get

resources:
  Resources:
    kinesisStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: teste
        RetentionPeriodHours: 24
        ShardCount: 1

